Update README.md
sudo add-apt-repository ppa:atareao\atareao   trigger following error: 
Cannot add PPA: 'ppa:~atareaoatareao/ubuntu/ppa'.
ERROR: '~atareaoatareao' user or team does not exist.

You should use Slash (/) instead of Backslash(\) 
fix: sudo add-apt-repository ppa:atareao/atareao